### PR TITLE
Shake sensor

### PR DESCRIPTION
**Pull request by magicvilla**
My reflections on how this week's project turned out:
I would really like to later on dive deeper into react native even though i thought this weeks project was hard.
Mainly due to understanding the Shakesensor logic and how to style styled components fully.
Overall i am happy what i have brought to the table.

Things I'd like to have clarified or explained in more detail:
More about react native overall. How to style the parts that you take for granted with regular CSS files.

https://expo.io/@magicvilla/projects/project-react-native-app

### CODE REVIEW

**Review by KarolCislowski — CHANGES_REQUESTED** [review]
unfortunately, I couldn't run your app via the link, because you used an outdated version of SDK. 
I tried to download your code and build it locally, but I couldn't even install it and I get an error:

```bash
error font@0.0.4: The engine "node" is incompatible with this module. Expected version "0.6". Got "15.10.0"
error Found incompatible module.
```

**Comment by magicvilla** [comment]
Hi karol! Thank you for the feedback! I don’t know what I should do to fix these changes. I think a lot of people had issues with the iOS. I don’t know what I need to update. It worked for me before and we didn’t get any information about how to fix these things unfortunately. What do I need to do to get approved?

**Comment by magicvilla** [comment]
Hi @KarolCislowski i added it to the snack expo instead : https://snack.expo.io/@magicvilla/excuse-app

**Review by KarolCislowski — APPROVED** [review]
Nice app 🥇

**Pull request closed without merging**
